"""v2 full data model: core/gst/extraction schemas

Revision ID: 0d70cc869b18
Revises:
Create Date: 2026-09-26 18:59:04.807649

Autogenerated table/index DDL with hand-added enum-type management (SAEnum
types are created/dropped explicitly — autogenerate omits them).
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0d70cc869b18"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# (schema, type_name, values) — every PG enum used by the v2 model.
ENUMS: list[tuple[str, str, tuple[str, ...]]] = [
    ("core", "firm_role", ("PARTNER", "CA", "CLERK")),
    ("core", "business_role", ("OWNER", "CLERK")),
    ("core", "link_status", ("PENDING", "ACTIVE", "REJECTED", "REVOKED")),
    ("core", "link_initiated_by", ("FIRM_REQUEST", "CLIENT_INVITE")),
    ("core", "filing_scheme", ("REGULAR_MONTHLY", "QRMP", "COMPOSITION")),
    (
        "gst",
        "invoice_direction",
        ("SALES", "PURCHASE"),
    ),
    ("gst", "supply_type", ("INTRA", "INTER")),
    ("gst", "invoice_status", ("DRAFT", "CONFIRMED", "LOCKED")),
    ("gst", "series_doc_type", ("INV", "CDN", "DBN")),
    ("gst", "inv_typ", ("R", "SEWP", "SEWOP", "DE")),
    ("gst", "export_pay_type", ("WPAY", "WOPAY")),
    ("gst", "filing_status", ("OPEN", "READY_FOR_FILING", "FILED")),
    ("gst", "note_type", ("CDN", "DBN")),
    ("gst", "note_status", ("DRAFT", "CONFIRMED", "LOCKED")),
    ("gst", "gstr1_export_type", ("ORIGINAL", "AMENDMENT")),
    ("gst", "amendment_status", ("DRAFT", "CONFIRMED", "EXPORTED")),
    ("gst", "gstr2b_source", ("PORTAL_UPLOAD", "GSP_API")),
    (
        "gst",
        "match_status",
        ("MATCHED", "PROBABLE", "UNMATCHED", "MISSING_IN_2B", "MISSING_IN_BOOKS"),
    ),
    ("extraction", "capture_source", ("PDF_SCAN", "DIGITAL", "PHOTO", "WHATSAPP")),
    (
        "extraction",
        "job_status",
        (
            "QUEUED",
            "PREPROCESS",
            "OCR_RUNNING",
            "LLM_RUNNING",
            "EXTRACTED",
            "FAILED",
            "NEEDS_REVIEW",
            "CONFIRMED",
        ),
    ),
]


def upgrade() -> None:
    """Upgrade schema."""
    # Enum types are created automatically by the per-table create events
    # (alembic's create_table fires before_create with a per-run memo so each
    # enum is emitted exactly once). Manual creation here would collide with
    # the events' unconditional CREATE TYPE (checkfirst=False).
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ca_firms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("firm_name", sa.String(length=255), nullable=False),
        sa.Column("ca_code", sa.String(length=30), nullable=False),
        sa.Column("pan", sa.String(length=10), nullable=False),
        sa.Column("gstin", sa.String(length=15), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ca_firms")),
        sa.UniqueConstraint("ca_code", name=op.f("uq_ca_firms_ca_code")),
        schema="core",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mobile", sa.String(length=15), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("mobile_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("totp_secret", sa.String(length=255), nullable=True),
        sa.Column("totp_enabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("mobile", name=op.f("uq_users_mobile")),
        schema="core",
    )
    op.create_table(
        "businesses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pan", sa.String(length=10), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("trade_name", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["core.users.id"], name=op.f("fk_businesses_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_businesses")),
        sa.UniqueConstraint("pan", name=op.f("uq_businesses_pan")),
        schema="core",
    )
    op.create_table(
        "ca_firm_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("firm_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "PARTNER", "CA", "CLERK", name="firm_role", schema="core"
            ),
            nullable=False,
        ),
        sa.Column("can_export", sa.Boolean(), nullable=False),
        sa.Column("can_revoke", sa.Boolean(), nullable=False),
        sa.Column("can_invite_members", sa.Boolean(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["firm_id"], ["core.ca_firms.id"], name=op.f("fk_ca_firm_members_firm_id_ca_firms")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["core.users.id"], name=op.f("fk_ca_firm_members_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ca_firm_members")),
        sa.UniqueConstraint("firm_id", "user_id", name="uq_ca_firm_members_firm_user"),
        schema="core",
    )
    op.create_table(
        "consent_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("principal_user_id", sa.Uuid(), nullable=False),
        sa.Column("fiduciary_type", sa.String(length=30), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("consent_text_version", sa.String(length=20), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["principal_user_id"],
            ["core.users.id"],
            name=op.f("fk_consent_records_principal_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_records")),
        schema="core",
    )
    op.create_table(
        "business_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "CLERK", name="business_role", schema="core"),
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["core.businesses.id"],
            name=op.f("fk_business_users_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["core.users.id"], name=op.f("fk_business_users_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_users")),
        sa.UniqueConstraint("business_id", "user_id", name="uq_business_users_biz_user"),
        schema="core",
    )
    op.create_table(
        "ca_client_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ca_firm_id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "ACTIVE", "REJECTED", "REVOKED",
                name="link_status", schema="core",
            ),
            nullable=False,
        ),
        sa.Column(
            "initiated_by",
            sa.Enum(
                "FIRM_REQUEST", "CLIENT_INVITE",
                name="link_initiated_by", schema="core",
            ),
            nullable=False,
        ),
        sa.Column("invite_code", sa.String(length=64), nullable=True),
        sa.Column("consent_record_id", sa.Uuid(), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["core.businesses.id"],
            name=op.f("fk_ca_client_links_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["ca_firm_id"],
            ["core.ca_firms.id"],
            name=op.f("fk_ca_client_links_ca_firm_id_ca_firms"),
        ),
        sa.ForeignKeyConstraint(
            ["consent_record_id"],
            ["core.consent_records.id"],
            name=op.f("fk_ca_client_links_consent_record_id_consent_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ca_client_links")),
        sa.UniqueConstraint("invite_code", name=op.f("uq_ca_client_links_invite_code")),
        schema="core",
    )
    op.create_index(
        "ix_ca_client_links_firm_business_status",
        "ca_client_links",
        ["ca_firm_id", "business_id", "status"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "gst_registrations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("gstin", sa.String(length=15), nullable=False),
        sa.Column("state_code", sa.String(length=2), nullable=False),
        sa.Column(
            "filing_scheme",
            sa.Enum(
                "REGULAR_MONTHLY", "QRMP", "COMPOSITION",
                name="filing_scheme", schema="core",
            ),
            nullable=False,
        ),
        sa.Column("irn_applicable", sa.Boolean(), nullable=False),
        sa.Column("aato_latest_minor", sa.BigInteger(), nullable=False),
        sa.Column("registered_address", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["core.businesses.id"],
            name=op.f("fk_gst_registrations_business_id_businesses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gst_registrations")),
        sa.UniqueConstraint("gstin", name=op.f("uq_gst_registrations_gstin")),
        schema="core",
    )
    op.create_index(
        "ix_gst_registrations_business",
        "gst_registrations",
        ["business_id"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("ca_firm_id", sa.Uuid(), nullable=True),
        sa.Column("business_id", sa.Uuid(), nullable=True),
        sa.Column("registration_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("payload_diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["core.users.id"], name=op.f("fk_audit_logs_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["core.businesses.id"],
            name=op.f("fk_audit_logs_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["ca_firm_id"],
            ["core.ca_firms.id"],
            name=op.f("fk_audit_logs_ca_firm_id_ca_firms"),
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["core.gst_registrations.id"],
            name=op.f("fk_audit_logs_registration_id_gst_registrations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
        schema="core",
    )
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity", "entity_id"],
        unique=False, schema="core",
    )
    op.create_index("ix_audit_logs_at", "audit_logs", ["at"], unique=False, schema="core")
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["core.businesses.id"],
            name=op.f("fk_notifications_business_id_businesses"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["core.users.id"], name=op.f("fk_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        schema="gst",
    )
    op.create_index(
        "ix_notifications_user_created", "notifications", ["user_id", "created_at"],
        unique=False, schema="gst",
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("fp", sa.String(length=6), nullable=False),
        sa.Column(
            "capture_source",
            sa.Enum(
                "PDF_SCAN", "DIGITAL", "PHOTO", "WHATSAPP",
                name="capture_source", schema="extraction",
            ),
            nullable=False,
        ),
        sa.Column("doc_type", sa.String(length=16), nullable=False),
        sa.Column("minio_key", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["core.gst_registrations.id"],
            name=op.f("fk_documents_registration_id_gst_registrations"),
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["core.users.id"], name=op.f("fk_documents_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        schema="extraction",
    )
    op.create_index(
        "ix_documents_reg_fp", "documents", ["registration_id", "fp"],
        unique=False, schema="extraction",
    )
    op.create_index(
        "ix_documents_sha256", "documents", ["sha256"], unique=False, schema="extraction"
    )
    op.create_table(
        "document_series",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column(
            "doc_type",
            sa.Enum("INV", "CDN", "DBN", name="series_doc_type", schema="gst"),
            nullable=False,
        ),
        sa.Column("series_code", sa.String(length=20), nullable=False),
        sa.Column("fy", sa.String(length=7), nullable=False),
        sa.Column("current_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["core.gst_registrations.id"],
            name=op.f("fk_document_series_registration_id_gst_registrations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_series")),
        sa.UniqueConstraint(
            "registration_id", "doc_type", "series_code", "fy",
            name="uq_document_series_reg_type_code_fy",
        ),
        schema="gst",
    )
    op.create_table(
        "filing_periods",
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("fp", sa.String(length=6), nullable=False),
        sa.Column("scheme_snapshot", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN", "READY_FOR_FILING", "FILED",
                name="filing_status", schema="gst",
            ),
            nullable=False,
        ),
        sa.Column("gstr1_due_date", sa.Date(), nullable=True),
        sa.Column("gstr3b_due_date", sa.Date(), nullable=True),
        sa.Column("iff_eligible", sa.Boolean(), nullable=False),
        sa.Column("nil_return", sa.Boolean(), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filed_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["filed_by"], ["core.users.id"], name=op.f("fk_filing_periods_filed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["core.gst_registrations.id"],
            name=op.f("fk_filing_periods_registration_id_gst_registrations"),
        ),
        sa.PrimaryKeyConstraint("registration_id", "fp", name=op.f("pk_filing_periods")),
        schema="gst",
    )
    op.create_table(
        "gstr1_exports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("fp", sa.String(length=6), nullable=False),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.Column("json_minio_key", sa.String(length=512), nullable=False),
        sa.Column("invoice_count", sa.Integer(), nullable=False),
        sa.Column("totals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column(
            "export_type",
            sa.Enum(
                "ORIGINAL", "AMENDMENT", name="gstr1_export_type", schema="gst"
            ),
            nullable=False,
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"], ["core.users.id"], name=op.f("fk_gstr1_exports_generated_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["core.gst_registrations.id"],
            name=op.f("fk_gstr1_exports_registration_id_gst_registrations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gstr1_exports")),
        schema="gst",
    )
    op.create_index(
        "ix_gstr1_exports_reg_fp", "gstr1_exports", ["registration_id", "fp"],
        unique=False, schema="gst",
    )
    op.create_table(
        "gstr2b_statements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("fp", sa.String(length=6), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "PORTAL_UPLOAD", "GSP_API", name="gstr2b_source", schema="gst"
            ),
            nullable=False,
        ),
        sa.Column("raw_minio_key", sa.String(length=512), nullable=False),
        sa.Column(
            "downloaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("imported_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["imported_by"],
            ["core.users.id"],
            name=op.f("fk_gstr2b_statements_imported_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["core.gst_registrations.id"],
            name=op.f("fk_gstr2b_statements_registration_id_gst_registrations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gstr2b_statements")),
        sa.UniqueConstraint(
            "registration_id", "fp", name="uq_gstr2b_statements_reg_fp"
        ),
        schema="gst",
    )
    op.create_table(
        "gstr3b_exports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("fp", sa.String(length=6), nullable=False),
        sa.Column("auto_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("manual_overrides", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"], ["core.users.id"], name=op.f("fk_gstr3b_exports_generated_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["core.gst_registrations.id"],
            name=op.f("fk_gstr3b_exports_registration_id_gst_registrations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gstr3b_exports")),
        sa.UniqueConstraint("registration_id", "fp", name="uq_gstr3b_exports_reg_fp"),
        schema="gst",
    )
    op.create_table(
        "extraction_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED", "PREPROCESS", "OCR_RUNNING", "LLM_RUNNING",
                "EXTRACTED", "FAILED", "NEEDS_REVIEW", "CONFIRMED",
                name="job_status", schema="extraction",
            ),
            nullable=False,
        ),
        sa.Column("preproc_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ocr_text_ref", sa.String(length=512), nullable=True),
        sa.Column("raw_llm_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("llm_model", sa.String(length=64), nullable=True),
        sa.Column("llm_tokens_in", sa.Integer(), nullable=True),
        sa.Column("llm_tokens_out", sa.Integer(), nullable=True),
        sa.Column("confidence_avg", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["extraction.documents.id"],
            name=op.f("fk_extraction_jobs_document_id_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_jobs")),
        schema="extraction",
    )
    op.create_index(
        "ix_extraction_jobs_status", "extraction_jobs", ["status"],
        unique=False, schema="extraction",
    )
    op.create_index(
        "ix_extraction_jobs_document", "extraction_jobs", ["document_id"],
        unique=False, schema="extraction",
    )
    op.create_table(
        "gstr2b_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("statement_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_gstin", sa.String(length=15), nullable=False),
        sa.Column("invoice_no", sa.String(length=32), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("taxable_value_minor", sa.Integer(), nullable=False),
        sa.Column("cgst_minor", sa.Integer(), nullable=False),
        sa.Column("sgst_minor", sa.Integer(), nullable=False),
        sa.Column("igst_minor", sa.Integer(), nullable=False),
        sa.Column("cess_minor", sa.Integer(), nullable=False),
        sa.Column("itc_eligible", sa.Boolean(), nullable=False),
        sa.Column("doc_type", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["gst.gstr2b_statements.id"],
            name=op.f("fk_gstr2b_entries_statement_id_gstr2b_statements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gstr2b_entries")),
        schema="gst",
    )
    op.create_index(
        "ix_gstr2b_entries_statement", "gstr2b_entries", ["statement_id"],
        unique=False, schema="gst",
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("fp", sa.String(length=6), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "SALES", "PURCHASE", name="invoice_direction", schema="gst"
            ),
            nullable=False,
        ),
        sa.Column("supplier_gstin", sa.String(length=15), nullable=True),
        sa.Column("buyer_gstin", sa.String(length=15), nullable=True),
        sa.Column("invoice_no", sa.String(length=32), nullable=False),
        sa.Column("series", sa.String(length=20), nullable=True),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("place_of_supply", sa.String(length=2), nullable=False),
        sa.Column(
            "supply_type",
            sa.Enum("INTRA", "INTER", name="supply_type", schema="gst"),
            nullable=False,
        ),
        sa.Column("rchrg", sa.Boolean(), nullable=False),
        sa.Column(
            "inv_typ",
            sa.Enum("R", "SEWP", "SEWOP", "DE", name="inv_typ", schema="gst"),
            nullable=False,
        ),
        sa.Column(
            "export_pay_type",
            sa.Enum("WPAY", "WOPAY", name="export_pay_type", schema="gst"),
            nullable=True,
        ),
        sa.Column("shipping_bill_no", sa.String(length=32), nullable=True),
        sa.Column("port_code", sa.String(length=10), nullable=True),
        sa.Column("total_value_minor", sa.Integer(), nullable=False),
        sa.Column("source_doc_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "CONFIRMED", "LOCKED", name="invoice_status", schema="gst"
            ),
            nullable=False,
        ),
        sa.Column("confirmed_by", sa.Uuid(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"], ["core.users.id"], name=op.f("fk_invoices_confirmed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["core.gst_registrations.id"],
            name=op.f("fk_invoices_registration_id_gst_registrations"),
        ),
        sa.ForeignKeyConstraint(
            ["source_doc_id"],
            ["extraction.documents.id"],
            name=op.f("fk_invoices_source_doc_id_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("registration_id", "fp", "invoice_no", name="uq_invoices_reg_fp_no"),
        schema="gst",
    )
    op.create_index(
        "ix_invoices_reg_fp", "invoices", ["registration_id", "fp"],
        unique=False, schema="gst",
    )
    op.create_table(
        "invoice_drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("extraction_job_id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("fp", sa.String(length=6), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("field_confidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["extraction_job_id"],
            ["extraction.extraction_jobs.id"],
            name=op.f("fk_invoice_drafts_extraction_job_id_extraction_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["core.gst_registrations.id"],
            name=op.f("fk_invoice_drafts_registration_id_gst_registrations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_drafts")),
        schema="extraction",
    )
    op.create_index(
        "ix_invoice_drafts_job", "invoice_drafts", ["extraction_job_id"],
        unique=False, schema="extraction",
    )
    op.create_table(
        "credit_debit_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("fp", sa.String(length=6), nullable=False),
        sa.Column(
            "note_type",
            sa.Enum("CDN", "DBN", name="note_type", schema="gst"),
            nullable=False,
        ),
        sa.Column("reason_code", sa.String(length=16), nullable=False),
        sa.Column("source_invoice_id", sa.Uuid(), nullable=True),
        sa.Column("buyer_gstin", sa.String(length=15), nullable=True),
        sa.Column("party_name", sa.String(length=255), nullable=True),
        sa.Column("taxable_value_minor", sa.Integer(), nullable=False),
        sa.Column("cgst_minor", sa.Integer(), nullable=False),
        sa.Column("sgst_minor", sa.Integer(), nullable=False),
        sa.Column("igst_minor", sa.Integer(), nullable=False),
        sa.Column("cess_minor", sa.Integer(), nullable=False),
        sa.Column("series", sa.String(length=20), nullable=True),
        sa.Column("note_no", sa.String(length=32), nullable=False),
        sa.Column("note_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "CONFIRMED", "LOCKED", name="note_status", schema="gst"
            ),
            nullable=False,
        ),
        sa.Column("irn", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["core.gst_registrations.id"],
            name=op.f("fk_credit_debit_notes_registration_id_gst_registrations"),
        ),
        sa.ForeignKeyConstraint(
            ["source_invoice_id"],
            ["gst.invoices.id"],
            name=op.f("fk_credit_debit_notes_source_invoice_id_invoices"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_debit_notes")),
        schema="gst",
    )
    op.create_index(
        "ix_credit_debit_notes_reg_fp", "credit_debit_notes", ["registration_id", "fp"],
        unique=False, schema="gst",
    )
    op.create_table(
        "e_invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("irn", sa.String(length=64), nullable=False),
        sa.Column("ack_no", sa.String(length=32), nullable=True),
        sa.Column("ack_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signed_qr_base64", sa.Text(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_window_until", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["gst.invoices.id"], name=op.f("fk_e_invoices_invoice_id_invoices")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_e_invoices")),
        sa.UniqueConstraint("invoice_id", name=op.f("uq_e_invoices_invoice_id")),
        sa.UniqueConstraint("irn", name=op.f("uq_e_invoices_irn")),
        schema="gst",
    )
    op.create_table(
        "invoice_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hsn_sac", sa.String(length=8), nullable=True),
        sa.Column("uqc", sa.String(length=3), nullable=True),
        sa.Column("qty", sa.Numeric(precision=18, scale=3), nullable=True),
        sa.Column("unit_price_minor", sa.Integer(), nullable=True),
        sa.Column("gst_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("taxable_value_minor", sa.Integer(), nullable=False),
        sa.Column("cgst_minor", sa.Integer(), nullable=False),
        sa.Column("sgst_minor", sa.Integer(), nullable=False),
        sa.Column("igst_minor", sa.Integer(), nullable=False),
        sa.Column("cess_minor", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["gst.invoices.id"], name=op.f("fk_invoice_lines_invoice_id_invoices")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_lines")),
        sa.UniqueConstraint("invoice_id", "line_no", name="uq_invoice_lines_inv_line"),
        schema="gst",
    )
    op.create_table(
        "itc_reconciliation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("fp", sa.String(length=6), nullable=False),
        sa.Column("purchase_invoice_id", sa.Uuid(), nullable=True),
        sa.Column("gstr2b_entry_id", sa.Uuid(), nullable=True),
        sa.Column(
            "match_status",
            sa.Enum(
                "MATCHED", "PROBABLE", "UNMATCHED", "MISSING_IN_2B", "MISSING_IN_BOOKS",
                name="match_status", schema="gst",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gstr2b_entry_id"],
            ["gst.gstr2b_entries.id"],
            name=op.f("fk_itc_reconciliation_gstr2b_entry_id_gstr2b_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["purchase_invoice_id"],
            ["gst.invoices.id"],
            name=op.f("fk_itc_reconciliation_purchase_invoice_id_invoices"),
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["core.gst_registrations.id"],
            name=op.f("fk_itc_reconciliation_registration_id_gst_registrations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_itc_reconciliation")),
        schema="gst",
    )
    op.create_index(
        "ix_itc_reconciliation_reg_fp", "itc_reconciliation", ["registration_id", "fp"],
        unique=False, schema="gst",
    )
    op.create_table(
        "gstr1a_amendments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("target_export_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=True),
        sa.Column("cdn_id", sa.Uuid(), nullable=True),
        sa.Column("field_deltas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "CONFIRMED", "EXPORTED", name="amendment_status", schema="gst"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exported_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["cdn_id"],
            ["gst.credit_debit_notes.id"],
            name=op.f("fk_gstr1a_amendments_cdn_id_credit_debit_notes"),
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["gst.invoices.id"],
            name=op.f("fk_gstr1a_amendments_invoice_id_invoices"),
        ),
        sa.ForeignKeyConstraint(
            ["target_export_id"],
            ["gst.gstr1_exports.id"],
            name=op.f("fk_gstr1a_amendments_target_export_id_gstr1_exports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gstr1a_amendments")),
        schema="gst",
    )
    # ### end Alembic commands ###


def _drop_enums() -> None:
    # Table after_drop events can't drop enums here: the column enums carry no
    # MetaData (NamedType._on_table_drop asserts metadata is not None), so
    # explicit reverse-order drops keep downgrade idempotent.
    from sqlalchemy.dialects.postgresql import ENUM

    for schema, name, values in reversed(ENUMS):
        enum_type = ENUM(*values, name=name, schema=schema, create_type=False)
        enum_type.drop(op.get_bind(), checkfirst=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gstr1a_amendments", schema="gst")
    op.drop_index("ix_itc_reconciliation_reg_fp", table_name="itc_reconciliation", schema="gst")
    op.drop_table("itc_reconciliation", schema="gst")
    op.drop_table("invoice_lines", schema="gst")
    op.drop_table("e_invoices", schema="gst")
    op.drop_index("ix_credit_debit_notes_reg_fp", table_name="credit_debit_notes", schema="gst")
    op.drop_table("credit_debit_notes", schema="gst")
    op.drop_index("ix_invoice_drafts_job", table_name="invoice_drafts", schema="extraction")
    op.drop_table("invoice_drafts", schema="extraction")
    op.drop_index("ix_invoices_reg_fp", table_name="invoices", schema="gst")
    op.drop_table("invoices", schema="gst")
    op.drop_index("ix_gstr2b_entries_statement", table_name="gstr2b_entries", schema="gst")
    op.drop_table("gstr2b_entries", schema="gst")
    op.drop_index("ix_extraction_jobs_status", table_name="extraction_jobs", schema="extraction")
    op.drop_index("ix_extraction_jobs_document", table_name="extraction_jobs", schema="extraction")
    op.drop_table("extraction_jobs", schema="extraction")
    op.drop_table("gstr3b_exports", schema="gst")
    op.drop_table("gstr2b_statements", schema="gst")
    op.drop_index("ix_gstr1_exports_reg_fp", table_name="gstr1_exports", schema="gst")
    op.drop_table("gstr1_exports", schema="gst")
    op.drop_table("filing_periods", schema="gst")
    op.drop_table("document_series", schema="gst")
    op.drop_index("ix_documents_sha256", table_name="documents", schema="extraction")
    op.drop_index("ix_documents_reg_fp", table_name="documents", schema="extraction")
    op.drop_table("documents", schema="extraction")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs", schema="core")
    op.drop_index("ix_audit_logs_at", table_name="audit_logs", schema="core")
    op.drop_table("audit_logs", schema="core")
    op.drop_index("ix_notifications_user_created", table_name="notifications", schema="gst")
    op.drop_table("notifications", schema="gst")
    op.drop_index("ix_gst_registrations_business", table_name="gst_registrations", schema="core")
    op.drop_table("gst_registrations", schema="core")
    op.drop_index(
        "ix_ca_client_links_firm_business_status", table_name="ca_client_links", schema="core"
    )
    op.drop_table("ca_client_links", schema="core")
    op.drop_table("business_users", schema="core")
    op.drop_table("consent_records", schema="core")
    op.drop_table("ca_firm_members", schema="core")
    op.drop_table("businesses", schema="core")
    op.drop_table("users", schema="core")
    op.drop_table("ca_firms", schema="core")
    # ### end Alembic commands ###
    _drop_enums()
